export const metadata = {
    title: "Titaoja",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <div className=" bg-gray-200 dark:bg-gray-600  bar">
            {children}
        </div>
    );
}
