let suggestions = [
  "iPhone",
  "Samsung TV",
  "Sony headphones",
  "Xbox",
  "Nike shoes",
  "Levi's jeans",
  "Gucci bag",
  "Ray-Ban sunglasses",
  "MAC lipstick",
  "Nivea cream",
  "L'Oreal shampoo",
  "Maybelline mascara",
  "IKEA furniture",
  "Samsung refrigerator",
  "LG washing machine",
  "Sony speaker",
  "Fitbit tracker",
  "Apple watch",
  "Nike fitness shoes",
  "Philips air purifier",
  "Pampers diapers",
  "Johnson's baby oil",
  "Gerber food",
  "Fisher-Price toys",
  "Adidas sneakers",
  "Under Armour jacket",
  "Calvin Klein underwear",
  "Estee Lauder foundation",
  "Canon camera",
  "Sony PlayStation",
  "Microsoft Surface",
  "Nike basketball",
  "The North Face jacket",
  "Chanel perfume",
  "Omega watch",
  "LG TV",
  "Samsung smartphone",
  "Asus laptop",
  "HP printer",
  "Apple iPad",
  "Sony music player",
  "JBL speakers",
  "GoPro camera",
  "Brother sewing machine",
  "KitchenAid mixer",
  "Nike running shoes",
  "New Balance sneakers",
  "Vans skateboarding shoes",
  "Ralph Lauren polo",
  "Uniqlo t-shirt",
  "Zara dress",
  "H&M jeans",
  "Levi's 501",
  "Ray-Ban aviators",
  "Oakley sunglasses",
  "Nike Air Force",
  "Converse Chuck Taylor",
  "Vans Old Skool",
  "Timberland boots",
  "Dr. Martens shoes",
  "Calvin Klein bra",
  "Victoria's Secret lingerie",
  "Chanel No. 5",
  "Dior perfume",
  "Tommy Hilfiger shirt",
  "Gap jeans",
  " Banana Republic dress",
  "Old Navy t-shirt",
  "Nike swoosh",
  "Adidas superstar",
  "Reebok crossfit",
  "Under Armour curry",
  "Nike vapor",
  "New Balance 574",
  "Asics running",
  "Brooks ghost",
  "Nike free",
  "Adidas ultraboost",
  "Reebok classic",
  "Sony wireless headphones",
  "Beats by Dre",
  "BOSE speakers",
  "JBL waterproof",
  "Sony over-ear",
  "Sennheiser microphone",
  "Audio-Technica turntable",
  "Panasonic camera",
  "Canon EOS",
  "Nikon DSLR",
  "Sony Alpha",
  "Fuji film",
  "Leica camera",
  "Apple AirPods",
  "Samsung earbuds",
  "Google pixel",
  "Sony Xperia",
  "LG G7",
  "Motorola smartphone",
  "Nike sportswear",
  "Adidas athletics",
  "Reebok fitness",
  "Under Armour training",
  "New Balance walking",
  "Asics gel",
  "Brooks running",
  "Nike tennis",
  "Wilson tennis racket",
  "Prince tennis shoes",
  "Babolat tennis strings",
  "Yonex badminton",
  "Spalding basketball",
  "Mizuno volleyball",
  "Nike golf",
  "Callaway golf clubs",
  "TaylorMade golf balls",
  "Nike cricket",
  "Adidas soccer",
  "Puma football",
  "Reebok crossfit games",
  "Under Armour marathon",
  "New Balance triathlon",
  "Asics track",
  "Brooks trail",
  "Nike water shoes",
  "Tevas sandals",
  "Sanuk flip flops",
  "Vans surfboard",
  "Quiksilver surfwear",
  "Roxy snowboard",
  "Burton snowboard",
  "The North Face thermoball",
  "Patagonia fleece",
  "Columbia outerwear",
  "The North Face venture",
  "Mountain Hardwear ghost",
  "Salomon hiking boots",
  "Merrell trail running",
  "Keen sandals",
  "Vibram fivefingers",
  "New Balance minimus",
  "Nike metcon",
  "Reebok crossfit nano",
  "Under Armour speedform",
  "Adidas adizero",
  "Asics gel-kayano",
  "Brooks ghost",
  "Nike vaporfly",
  "Apple watch series",
  "Samsung galaxy watch",
  "Fossil smartwatch",
  "Skagen smartwatch",
  "Tag Heuer connected",
  "Huawei watch gt",
  "Garmin forerunner",
  "Polar vantage",
  "Suunto 3 fitness",
  "Fitbit inspire",
  "Xiaomi mi band",
  "Sony smartwatch",
  "LG watch style",
  "Montblanc summit",
  "Hublot big bang",
  "Breitling navitimer",
  "Omega seamaster",
  "Rolex submariner",
  "Cartier tank",
  "TAG Heuer carrera",
  "IWC portuguese",
  "Panerai luminor",
  "Jaeger-LeCoultre reverso",
  "Blancpain fifty fathoms",
  "Breguet classique",
  "Chanel j12",
  "Dior christal",
  "Louis Vuitton tambour",
  "Gucci dive",
  "Hermes cape cod",
  "Prada sport",
  "Ray-Ban wayfarer",
  "Oakley holbrook",
  "Persol 0714",
  "Carrera sunglasses",
  "Maui jim ho'okipa",
];

export default suggestions;
